### ISSUE TITLE
[i18n] Validator

### ISSUE THREAD

**Issue by Demetri0** [dergunovs/mhz#5]
I guess that you may wrongly implement translations. According to documentation:
![Screenshot from 2023-07-23 18-40-30](https://github.com/dergunovs/mhz/assets/6806547/71398be8-6c1b-42cf-896c-55761a17cf3b)

... there is another way to provide translation. I believe that your [current way](https://github.com/dergunovs/mhz/blob/main/packages/validate/src/rules.ts#L1-L3) is not very useful, since you will need a lot of variations and different combinations of rules, and it seems too hard to make global rule for each place every time.

**Comment by dergunovs** [comment]
Hello. Thank you for this information. I decided to change the application language. Now its english. So im closing this issue.
